# Generated by Django 2.2.5 on 2019-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('course_number', models.PositiveIntegerField()),
                ('group_number', models.PositiveIntegerField()),
                ('teacher', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('first_day', models.DateField()),
                ('second_day', models.DateField(blank=True)),
            ],
        ),
    ]
