# Generated by Django 2.2.5 on 2019-11-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='first_day',
            field=models.IntegerField(choices=[(0, 'Saturday'), (3, 'Tuesday'), (4, 'Wednesday'), (2, 'Monday'), (1, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Saturday'), (3, 'Tuesday'), (4, 'Wednesday'), (2, 'Monday'), (1, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_date',
            field=models.DateField(),
        ),
    ]
